# Generated by Django 3.2.8 on 2021-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='departement',
            new_name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='lower_level_incharge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='top_level_incharge',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='battallion',
            field=models.CharField(choices=[('battallion_one', 'Battallion 1'), ('battallion_two', 'Battallion 2'), ('battallion_three', 'Battallion 3'), ('battallion_four', 'Battallion 4'), ('battallion_five', 'Battallion 5'), ('battallion_six', 'Battallion 6'), ('all_battallions', 'All Battallions')], max_length=32),
        ),
    ]
