# Generated by Django 3.2.8 on 2021-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211029_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lower_level_incharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='top_level_incharge',
            field=models.BooleanField(default=False),
        ),
    ]
