# Generated by Django 3.2.8 on 2021-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211030_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battallion_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('nin', models.CharField(max_length=32)),
                ('ipps', models.CharField(max_length=32)),
                ('file_number', models.CharField(max_length=32)),
                ('battallion', models.CharField(max_length=32)),
                ('account_number', models.CharField(blank=True, max_length=32, null=True)),
                ('contact', models.CharField(blank=True, max_length=32, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=32)),
                ('rank', models.CharField(choices=[('AIGP', 'AIGP'), ('SCP', 'SCP'), ('CP', 'CP'), ('ACP', 'ACP'), ('SSP', 'SSP'), ('SP', 'SP'), ('ASP', 'ASP'), ('IP', 'IP'), ('AIP', 'AIP'), ('SGT', 'SGT'), ('CPL', 'CPL'), ('PC', 'PC'), ('SPC', 'SPC')], max_length=32)),
                ('education_level', models.CharField(choices=[('ple', 'PLE'), ('uce', 'UCE'), ('uace', 'UACE'), ('diploma', 'DIPLOMA'), ('bachelors', 'BACHELORS'), ('masters', 'MASTERS'), ('doctorate', 'DOCTORATE(PhD)'), ('other', 'OTHER')], max_length=32)),
                ('other_education_level', models.CharField(blank=True, max_length=32, null=True)),
                ('bank', models.CharField(blank=True, max_length=32, null=True)),
                ('branch', models.CharField(blank=True, max_length=32, null=True)),
                ('department', models.CharField(choices=[('embassy', 'Embassy'), ('consolate', 'Consolate'), ('high_commission', 'High commission'), ('other_diplomats', 'Other diplomats'), ('administration', 'Administration')], max_length=32)),
                ('title', models.CharField(choices=[('commandant', 'Commandant'), ('deputy_commandant', 'Deputy commandant'), ('high_commission', 'High commission'), ('staff_officer', 'Staff officer'), ('head_of_operations', 'Head of operations'), ('head_of_armoury', 'Head of armoury'), ('supervisor', 'Supervisor'), ('in_Charge', 'In Charge'), ('2nd_in_charge', '2nd In Charge'), ('driver', 'Driver')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('absent', 'Absent(AWOL)'), ('transfered', 'Transfered'), ('sick', 'Sick'), ('dead', 'Dead'), ('suspended', 'Suspended'), ('dismissed', 'Dismissed'), ('in_court', 'In court'), ('deserted', 'Deserted'), ('on_course', 'On course'), ('on_mission', 'On mission')], max_length=32)),
                ('shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('long_night', 'Long night'), ('none', 'None(not applicable)')], max_length=32)),
                ('date_of_enlistment', models.DateField(blank=True, null=True)),
                ('date_of_transfer', models.DateField(blank=True, null=True)),
                ('date_of_promotion', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('armed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=32)),
                ('section', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('on_leave', models.CharField(choices=[('pass_leave', 'Pass leave'), ('maternity_leave', 'Maternity leave'), ('sick_leave', 'Sick leave'), ('study_leave', 'Study leave'), ('annual_leave', 'Annual leave'), ('not_no_leave', 'Not no leave')], max_length=32)),
                ('leave_start_date', models.DateField(blank=True, null=True)),
                ('leave_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
