# Generated by Django 3.2.8 on 2021-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_battallion_two'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battallion_two',
            options={'verbose_name': 'Battallion Two', 'verbose_name_plural': 'Battallion Two'},
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='file_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
