# Generated by Django 3.2.8 on 2021-11-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_battallion_two_on_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battallion_two',
            name='on_leave',
            field=models.CharField(choices=[('Pass leave', 'Pass leave'), ('Maternity leave', 'Maternity leave'), ('Sick leave', 'Sick leave'), ('Study leave', 'Study leave'), ('Annual leave', 'Annual leave'), ('Not on leave', 'Not on leave')], max_length=32),
        ),
    ]
