# Generated by Django 3.2.8 on 2021-12-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_user_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battallion_one',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Absent', 'Absent(AWOL)'), ('Transfered', 'Transfered'), ('Sick', 'Sick'), ('Dead', 'Dead'), ('Suspended', 'Suspended'), ('Dismissed', 'Dismissed'), ('In court', 'In court'), ('Deserted', 'Deserted'), ('On course', 'On course'), ('On mission', 'On mission'), ('On leave', 'On leave')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='department',
            field=models.CharField(choices=[('Embassy', 'Embassy'), ('Consulate', 'Consulate'), ('High commission', 'High commission'), ('Other diplomats', 'Other diplomats'), ('Administration', 'Administration')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Absent', 'Absent(AWOL)'), ('Transfered', 'Transfered'), ('Sick', 'Sick'), ('Dead', 'Dead'), ('Suspended', 'Suspended'), ('Dismissed', 'Dismissed'), ('In court', 'In court'), ('Deserted', 'Deserted'), ('On course', 'On course'), ('On mission', 'On mission'), ('On leave', 'On leave')], max_length=32),
        ),
    ]
