# Generated by Django 3.2.8 on 2021-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211204_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='battallion_one',
            name='tin_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='battallion_two',
            name='tin_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='battallion_one',
            name='education_level',
            field=models.CharField(choices=[('PLE', 'PLE'), ('UCE', 'UCE'), ('UACE', 'UACE'), ('Diploma', 'DIPLOMA'), ('Post Graduate Diploma', 'POST GRADUATE DIPLOMA'), ('Bachelors', 'BACHELORS'), ('Masters', 'MASTERS'), ('Doctorate', 'DOCTORATE(PhD)'), ('Other', 'OTHER')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battallion_one',
            name='section',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='battallion_one',
            name='title',
            field=models.CharField(choices=[('Commandant', 'Commandant'), ('Deputy commandant', 'Deputy commandant'), ('Staff officer', 'Staff officer'), ('Head of operations', 'Head of operations'), ('Head of armoury', 'Head of armoury'), ('Supervisor', 'Supervisor'), ('In Charge', 'In Charge'), ('2nd In Charge', '2nd In Charge'), ('Driver', 'Driver'), ('N/A', 'N/A')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='education_level',
            field=models.CharField(choices=[('PLE', 'PLE'), ('UCE', 'UCE'), ('UACE', 'UACE'), ('Diploma', 'DIPLOMA'), ('Post Graduate Diploma', 'POST GRADUATE DIPLOMA'), ('Bachelors', 'BACHELORS'), ('Masters', 'MASTERS'), ('Doctorate', 'DOCTORATE(PhD)'), ('Other', 'OTHER')], max_length=32),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='section',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='title',
            field=models.CharField(choices=[('Commandant', 'Commandant'), ('Deputy commandant', 'Deputy commandant'), ('Staff officer', 'Staff officer'), ('Head of operations', 'Head of operations'), ('Head of armoury', 'Head of armoury'), ('Supervisor', 'Supervisor'), ('In Charge', 'In Charge'), ('2nd In Charge', '2nd In Charge'), ('Driver', 'Driver'), ('N/A', 'N/A')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, choices=[('UNDP Head Office', 'UNDP Head Office'), ('UN Women', 'UN Women'), ('IFAD office', 'IFAD office'), ('UNDSS office', 'UNDSS office'), ('WFP', 'WFP'), ('WHO', 'WHO'), ('World bank', 'World bank'), ('FAO office', 'FAO office'), ('SPGS office', 'SPGS office'), ('UNHCR new offices', 'UNHCR new offices'), ('UNHCR Extension', 'UNHCR Extension'), ('I.C.C field offices', 'IFAD office'), ('UNFPA', 'UNFPA'), ('I.O.M head office', 'I.O.M head office'), ('I.O.M Transit Centre', 'I.O.M Transit Centre'), ('UNOHCHR office', 'UNOHCHR office'), ('EADB', 'EADB'), ('UNDP', 'UNDP'), ('UNDP Gulu', 'UNDP Gulu'), ('UNDP Moroto', 'UNDP Moroto'), ('UNICEF office', 'UNICEF office'), ('UNDP Arua', 'UNDP Arua')], max_length=150, null=True),
        ),
    ]
