# Generated by Django 3.2.8 on 2021-12-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211209_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='battallion_one',
            name='notify_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battallion_two',
            name='notify_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='battallion_one',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='battallion_two',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
