# Generated by Django 3.2.8 on 2021-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_deleted_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_employee',
            name='battalion',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
