# Generated by Django 3.2.8 on 2022-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220122_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='battallion_one',
            name='notify_special_duty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battallion_two',
            name='notify_special_duty',
            field=models.BooleanField(default=False),
        ),
    ]
