# Generated by Django 3.2.8 on 2022-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220201_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battallion_five',
            name='department',
            field=models.CharField(choices=[('UCC', 'UCC'), ('EC', 'EC'), ('IRA', 'IRA'), ('URA', 'URA'), ('UNRA', 'UNRA'), ('NPA', 'NPA'), ('ULC', 'ULC'), ('PSC', 'PSC'), ('NSSF', 'NSSF'), ('KCCA', 'KCCA'), ('SENIOR CITIZENS', 'SENIOR CITIZENS'), ('JSC', 'JSC')], max_length=150),
        ),
    ]
