# Generated by Django 3.2.8 on 2022-02-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_battallion_five_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Anti-corruption and War Crime division', 'Anti-corruption and War Crime division'), ('Buganda Road Court', 'Buganda Road Court'), ('Commercial court', 'Commercial court'), ('Supreme Court', 'Supreme Court'), ('High Court Offices Kampala', 'High Court Offices Kampala'), ('High Court Residence', 'High Court Residence'), ('Family Court Division Makindye', 'Family Court Division Makindye'), ('Court of Appeal', 'Court of Appeal'), ('Residence of Justice of Court Appeal', 'Residence of Justice of Court Appeal'), ('DPP Office', 'DPP Office'), ('IGG', 'IGG'), ('AOG', 'AOG'), ('Police Establishment', 'Police Establishment'), ('Body guard', 'Body guard'), ('Crew Commander', 'Crew Commander'), ('Crew', 'Crew'), ('UCC', 'UCC'), ('EC', 'EC'), ('IRA', 'IRA'), ('URA', 'URA'), ('UNRA', 'UNRA'), ('NPA', 'NPA'), ('ULC', 'ULC'), ('PSC', 'PSC'), ('NSSF', 'NSSF'), ('KCCA', 'KCCA'), ('SENIOR CITIZENS', 'SENIOR CITIZENS'), ('JSC', 'JSC')], max_length=150, null=True),
        ),
    ]
