# Generated by Django 3.2.8 on 2022-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220207_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_request_access',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='admin request access'),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_request_battalion',
            field=models.CharField(blank=True, choices=[('battallion_one', 'Battallion 1'), ('battallion_two', 'Battallion 2'), ('battallion_three', 'Battallion 3'), ('battallion_four', 'Battallion 4'), ('battallion_five', 'Battallion 5'), ('battallion_six', 'Battallion 6')], max_length=32, null=True),
        ),
    ]
