import notifications.urls
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_swagger.views import get_swagger_view

from api.views import (
    AccountLoginAPIView,
    SignUp,
    UserProfile,
    UserViewSet,
    ChangePasswordApi,
    UserType,
    BattallionTwoViewset,
    BattallionOneViewset,
    BattallionThreeViewset,
    BattallionFourViewset,
    BattallionFiveViewset,
    BattallionSixViewset,
    export_excel,
    export_excel_B_one,
    export_excel_B_three,
    export_excel_B_four,
    export_excel_B_five,
    export_excel_B_six,
    export_excel_B_one_section,
    export_excel_B_three_departmnt,
    export_excel_B_four_departmnt,
    export_excel_B_five_departmnt,
    export_excel_B_six_departmnt,
    export_excel_B_one_section_status,
    export_excel_B_three_department_status,
    export_excel_B_four_department_status,
    export_excel_B_five_department_status,
    export_excel_B_six_department_status,
    export_excel_B_one_section_leave,
    export_excel_B_three_department_leave,
    export_excel_B_four_department_leave,
    export_excel_B_five_department_leave,
    export_excel_B_six_department_leave,
    export_excel_B_two_status,
    export_excel_B_two_leave,
    export_excel_B_one_status,
    export_excel_B_three_status,
    export_excel_B_four_status,
    export_excel_B_five_status,
    export_excel_B_six_status,
    export_excel_B_one_leave,
    export_excel_B_three_leave,
    export_excel_B_four_leave,
    export_excel_B_five_leave,
    export_excel_B_six_leave,
    BattalionTwo_query,
    BattalionOne_query,
    BattalionThree_query,
    BattalionFour_query,
    BattalionFive_query,
    BattalionSix_query,
    BattalionTwo_overrall,
    BattalionThree_overrall,
    BattalionFour_overrall,
    BattalionFive_overrall,
    BattalionSix_overrall,
    BattalionOne_overrall,
    Vippu_Overrall,
    BattalionTwo_section_query,
    BattalionThree_department_query,
    BattalionFour_department_query,
    BattalionFive_department_query,
    BattalionSix_department_query,
    BattalionTwo_department_query,
    DeletedEmployeeViewset
)


router = DefaultRouter()
router.register(r"users", UserViewSet, basename="users")
router.register(r"battallion_two", BattallionTwoViewset, basename="battallion_two")
router.register(r"battallion_one", BattallionOneViewset, basename="battallion_one")
router.register(r"battallion_three", BattallionThreeViewset, basename="battallion_three")
router.register(r"battallion_four", BattallionFourViewset, basename="battallion_four")
router.register(r"battallion_five", BattallionFiveViewset, basename="battallion_five")
router.register(r"battallion_six", BattallionSixViewset, basename="battallion_six")
router.register(r"deleted_employees", DeletedEmployeeViewset, basename="deleted_employees")

schema_view = get_swagger_view(title="VIPPU API")

urlpatterns = [
    path("login/", AccountLoginAPIView.as_view(), name="login"),
    path("signup/", SignUp.as_view(), name="api-signup"),
    path("user_type_check/", UserType.as_view(), name="user-check"),
    path("battalionquery_two/", BattalionTwo_query.as_view(), name="battalionquery_two"),
    path("battalionquery_one/", BattalionOne_query.as_view(), name="battalionquery_one"),
    path("battalionquery_three/", BattalionThree_query.as_view(), name="battalionquery_three"),
    path("battalionquery_four/", BattalionFour_query.as_view(), name="battalionquery_four"),
    path("battalionquery_five/", BattalionFive_query.as_view(), name="battalionquery_five"),
    path("battalionquery_six/", BattalionSix_query.as_view(), name="battalionquery_six"),
    path("battaliontwo_overrall/", BattalionTwo_overrall.as_view(), name="battaliontwo_overrall"),
    path("battalionthree_overrall/", BattalionThree_overrall.as_view(), name="battalionthree_overrall"),
    path("battalionfour_overrall/", BattalionFour_overrall.as_view(), name="battalionfour_overrall"),
    path("battalionfive_overrall/", BattalionFive_overrall.as_view(), name="battalionfive_overrall"),
    path("battalionsix_overrall/", BattalionSix_overrall.as_view(), name="battalionsix_overrall"),
    path("battalionone_overrall/", BattalionOne_overrall.as_view(), name="battalionone_overrall"),
    path("vippu_overrall/", Vippu_Overrall.as_view(), name="vippu_overrall"),
    path("battalionone_section_query/", BattalionTwo_section_query.as_view(), name="battalionone_section_query"),
    path("battalion3_section_query/", BattalionThree_department_query.as_view(), name="battalion3_section_query"),
    path("battalion4_department_query/", BattalionFour_department_query.as_view(), name="battalion4_department_query"),
    path("battalion5_department_query/", BattalionFive_department_query.as_view(), name="battalion5_department_query"),
    path("battalion6_department_query/", BattalionSix_department_query.as_view(), name="battalion6_department_query"),
    path("battalion2_department_query/", BattalionTwo_department_query.as_view(), name="battalion2_department_query"),
    path("export_excel/", export_excel, name="export_excel"),
    path("export_battalion_one/", export_excel_B_one, name="export_battalion_one"),
    path("export_battalion_three/", export_excel_B_three, name="export_battalion_three"),
    path("export_battalion_four/", export_excel_B_four, name="export_battalion_four"),
    path("export_battalion_five/", export_excel_B_five, name="export_battalion_five"),
    path("export_battalion_six/", export_excel_B_six, name="export_battalion_six"),
    path("export_battalion_one_section/", export_excel_B_one_section, name="export_battalion_one_section"),
    path("export_battalion_three_department/", export_excel_B_three_departmnt, name="export_battalion_three_department"),
    path("export_battalion_four_department/", export_excel_B_four_departmnt, name="export_battalion_four_department"),
    path("export_battalion_five_department/", export_excel_B_five_departmnt, name="export_battalion_five_department"),
    path("export_battalion_six_department/", export_excel_B_six_departmnt, name="export_battalion_six_department"),
    path("export_battalion_one_section_status/", export_excel_B_one_section_status, name="export_battalion_one_section_status"),
    path("export_battalion_three_department_status/", export_excel_B_three_department_status, name="export_battalion_three_department_status"),
    path("export_battalion_four_department_status/", export_excel_B_four_department_status, name="export_battalion_four_department_status"),
    path("export_battalion_five_department_status/", export_excel_B_five_department_status, name="export_battalion_five_department_status"),
    path("export_battalion_six_department_status/", export_excel_B_six_department_status, name="export_battalion_six_department_status"),
    path("export_battalion_one_section_leave/", export_excel_B_one_section_leave, name="export_battalion_one_section_leave"),
    path("export_battalion_three_department_leave/", export_excel_B_three_department_leave, name="export_battalion_three_department_leave"),
    path("export_battalion_four_department_leave/", export_excel_B_four_department_leave, name="export_battalion_four_department_leave"),
    path("export_battalion_five_department_leave/", export_excel_B_five_department_leave, name="export_battalion_five_department_leave"),
    path("export_battalion_six_department_leave/", export_excel_B_six_department_leave, name="export_battalion_six_department_leave"),
    path("export_battalion_two_status/", export_excel_B_two_status, name="export_battalion_two_status"),
    path("export_battalion_two_leave/", export_excel_B_two_leave, name="export_battalion_two_leave"),
    path("export_battalion_one_status/", export_excel_B_one_status, name="export_battalion_one_status"),
    path("export_battalion_three_status/", export_excel_B_three_status, name="export_battalion_three_status"),
    path("export_battalion_four_status/", export_excel_B_four_status, name="export_battalion_four_status"),
    path("export_battalion_five_status/", export_excel_B_five_status, name="export_battalion_five_status"),
    path("export_battalion_six_status/", export_excel_B_six_status, name="export_battalion_six_status"),
    path("export_battalion_one_leave/", export_excel_B_one_leave, name="export_battalion_one_leave"),
    path("export_battalion_three_leave/", export_excel_B_three_leave, name="export_battalion_three_leave"),
    path("export_battalion_four_leave/", export_excel_B_four_leave, name="export_battalion_four_leave"),
    path("export_battalion_five_leave/", export_excel_B_five_leave, name="export_battalion_five_leave"),
    path("export_battalion_six_leave/", export_excel_B_six_leave, name="export_battalion_six_leave"),

    path("token/refresh/", refresh_jwt_token),
    path("users/me/", UserProfile.as_view()),
    path("auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("auth/", include("rest_framework_social_oauth2.urls")),
    path("auth/password/change/", ChangePasswordApi.as_view()),
    path("", include(router.urls)),
]


# path("auth/accounts/confirm/", AccountActivation.as_view()),
# path("auth/password/request/reset/", RequestPasswordReset.as_view()),
# path("auth/password/reset/request/confirm/", ConfirmPasswordResetRequest.as_view()),
# path("auth/password/reset/", ResetPasswordApi.as_view()),